config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'

  get 'destroy_all', to: 'home#destroy_all'
  get 'create_random_user', to: 'home#create_random_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :index, :get_users

  def index
  end

  def destroy_all
    User.all.destroy_all
    redirect_to root_path
  end

  def create_random_user
    RandomUserJob.perform_later
    redirect_to root_path
  end

  private

    def get_users
      @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <p><%= link_to 'Create Random User', create_random_user_path %></p>
  <p><%= link_to 'Destroy All Users', destroy_all_path %></p>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody class="demotable">
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekiqTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                                              crossorigin="anonymous"></script>
  </body>
</html>